#!/bin/sh

# Startup script for PRISM GUI (Linux/Solaris)

# PRISM home directory
PRISM_DIR="/Users/pablo/University/Tools/PrismGamesSrc/prism-games-master/prism"

# Launch using main PRISM script
PRISM_MAINCLASS=userinterface.GUIPrism
PRISM_HEADLESS=false
export PRISM_MAINCLASS PRISM_HEADLESS
$PRISM_DIR/Useful/prism "$@"
